#! /bin/bash

# Copyright (C) tanserver.org
# Copyright (C) Chen Daye

### BEGIN INIT INFO
# Provides:          tanshipper
# Required-Start:    $all
# Required-Stop:	 $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: control script
# Description:       control script
### END INIT INFO

NAME=tanshipper
PIDFILE=/var/run/tanshipper.pid
DAEMON=/usr/local/tanshipper/sbin/tanshipper

PID=$(head -n +1 $PIDFILE 2>/dev/null)

start() {
	kill -0 $PID 2>/dev/null || $DAEMON
}

stop() {
	kill -SIGTERM $PID 2>/dev/null && rm -rf $PIDFILE
	return $?
}

restart() {
    stop && sleep 0.1 && start
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
*)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
	exit 1
esac

exit 0
